name: 构建2.6webapp镜像

on:
  workflow_dispatch:  # 仅允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 清理Buildx环境
        run: |
          docker buildx prune -f
          docker buildx rm builder || true
          docker buildx create --name builder --use --driver docker-container
          docker buildx inspect --bootstrap

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 构建并推送到Dockerhub镜像仓库
        uses: docker/build-push-action@v5
        with:
          context: 2.6%20webapp%EF%BC%88%E6%B5%81%E5%BC%8F%E4%BC%A0%E8%BE%93%E6%B5%8B%E8%AF%95%E7%89%88%EF%BC%89
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/stock-webapp:latest
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          attest: false
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
