name: 构建2.6webapp镜像

on:
  workflow_dispatch:  # 仅允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置QEMU跨平台支持
        uses: docker/setup-qemu-action@v3

      - name: 设置Buildx构建器
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: 登录Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 构建并推送多平台镜像
        uses: docker/build-push-action@v5
        with:
          context: "2.6 webapp（流式传输测试版）"
          file: "2.6 webapp（流式传输测试版）/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/stock-webapp:latest
            ${{ secrets.DOCKER_USERNAME }}/stock-webapp:2.6-beta
          cache-from: type=gha
          cache-to: type=gha,mode=max
